distributable:
  url: https://github.com/pypa/pipenv/archive/refs/tags/v{{ version }}.tar.gz
  strip-components: 1

versions:
  - 2023.2.4

dependencies:
  python.org: '>=3.7'


build:
  dependencies:
    pip.pypa.io: '*'
    gnu.org/bash: '>=2'  # for our venv/relocation scripts: feel free to fix that

  script:
    python-venv.sh {{prefix}}/bin/pipenv

provides:
  - bin/pipenv

test:
  script: |
    pipenv --version

