distributable:
  url: https://github.com/royreznik/rexi/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: royreznik/rexi
dependencies:
  python.org: '>=3.8'

build:
  python-venv.sh {{prefix}}/bin/rexi

test:
  - rexi --help

provides:
  - bin/rexi
