distributable:
  url: https://github.com/pypa/twine/archive/refs/tags/{{ version }}.tar.gz
  strip-components: 1

versions:
  github: pypa/twine/releases/tags  # reads github *releases* but uses the tags of those releases
  strip: /^v/

dependencies:
  python.org: '>=3.7'

build:
  dependencies:
    pip.pypa.io: '*'
  script: |
    python-venv.sh {{prefix}}/bin/twine
    {{prefix}}/venv/bin/pip install --upgrade build
test:
  env:
    PYPI_PASSWORD: tea_password 
    PYPI_USERNAME: tea_username
  script: |
    twine --version
    which python

    mv $FIXTURE pyproject.toml
    {{prefix}}/venv/bin/python -m build
    twine check dist/*
  fixture: |
    # pyproject.toml
    [build-system]
    requires = ["setuptools>=61.0"]
    build-backend = "setuptools.build_meta"

    [project]
    name = "example_package"
    version = "0.0.1"
    authors = [
      { name="Example Author", email="author@example.com" },
    ]
    description = "A small example package"
    readme = "README.md"
    requires-python = ">=3.7"
    classifiers = [
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ]

    [project.urls]
    "Homepage" = "https://github.com/pypa/sampleproject"
    "Bug Tracker" = "https://github.com/pypa/sampleproject/issues"

provides:
  - bin/twine