distributable:
  url: https://codeload.github.com/ClementTsang/bottom/tar.gz/refs/tags/{{version}}
  strip-components: 1

provides:
  - bin/btm

versions:
  github: ClementTsang/bottom/tags
  strip: /v/

dependencies:
  zlib.net: ^1

build:
  dependencies:
    rust-lang.org: '>=1.60'
    rust-lang.org/cargo: '*'
  script:
    cargo install --locked --path . --root {{prefix}}

test:
  script: |
    test "$(btm --version)"="bottom {{version}}"

