# Tree is a recursive directory listing command that produces a depth indented listing of files, which is colorized
# brew formula: https://formulae.brew.sh/formula/tree

distributable:
  url: https://gitlab.com/OldManProgrammer/unix-tree/-/archive/{{version}}/unix-tree-{{version}}.tar.gz
  strip-components: 1

versions:
  - 2.1.0

build:
  dependencies:
    tea.xyz/gx/make: '*'
    linux:
        gnu.org/gcc: "*"
    darwin:
        tea.xyz/gx/cc: c99



  script: |
    make
    make $ARGS install

  env:
    ARGS:
      - PREFIX={{prefix}}
    LDFLAGS:
      - -s
    linux:
      CC: gcc
      CFLAGS: -O3

    darwin: #FIXME need to patch this and Makefile to build on OSX
      CC: cc
      CFLAGS: -O2 -Wall -fomit-frame-pointer -no-cpp-precomp




test:
  script: |
    # prepare for tests
    mkdir -p foo/bar
    mkdir -p foo/buzz
    touch foo/buzz/lupus.txt
    # run tests
    tree --version | grep 'tree v{{version}}'
    test "$(tree .)" = "$(cat $FIXTURE)"
  fixture: |
    .
    ├── foo
    │   ├── bar
    │   └── buzz
    │       └── lupus.txt
    ├── xyz.tea.fixture
    └── xyz.tea.test.sh

    4 directories, 3 files

provides:
  - bin/tree
